// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUQt8iCCr9ltIfx8PYUpnN7-RIWBpyk_s',
    appId: '1:742487955858:web:fecb73f78166d53d05494b',
    messagingSenderId: '742487955858',
    projectId: 'slingshotapp-839e0',
    authDomain: 'slingshotapp-839e0.firebaseapp.com',
    storageBucket: 'slingshotapp-839e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpeFipjk_8c8HH8mrUOJPRhhuy9IUSYCA',
    appId: '1:742487955858:android:546653b296d9bfb205494b',
    messagingSenderId: '742487955858',
    projectId: 'slingshotapp-839e0',
    storageBucket: 'slingshotapp-839e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHT520TwzyqrEPX7eMJoguajPm187WhIU',
    appId: '1:742487955858:ios:e96f1aa3e354cd5005494b',
    messagingSenderId: '742487955858',
    projectId: 'slingshotapp-839e0',
    storageBucket: 'slingshotapp-839e0.appspot.com',
    iosBundleId: 'com.example.slingshot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHT520TwzyqrEPX7eMJoguajPm187WhIU',
    appId: '1:742487955858:ios:2e2cbb8ddcad9bda05494b',
    messagingSenderId: '742487955858',
    projectId: 'slingshotapp-839e0',
    storageBucket: 'slingshotapp-839e0.appspot.com',
    iosBundleId: 'com.example.slingshot.RunnerTests',
  );
}
